language: android
dist: trusty

android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

before_install:
 - chmod +x gradlew
jdk:
  - oraclejdk8
script:
  - ./gradlew testDebug
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - echo yes | sdkmanager "build-tools;28.0.3"
  - - chmod +x gradlew
env:
 global:
 - ANDROID_API=28
 - ANDROID_BUILD_TOOLS=28.0.3
